#!/bin/sh
# Wrapper script to run the SLAS demo protocol with correct
# environment variables. Should be installed to path; run with
# slas_demo
orig=$(pwd)
cd /opt/opentrons-robot-server
OT_API_FF_enableOT3HardwareController="true" RUNNING_ON_VERDIN=1 OT_SYSTEM_VERSION="0.0.0" opentrons_execute /opt/opentrons-robot-server/opentrons/drivers/stacker/slas_demo.py && cd ${orig} || cd ${orig}
