import { RUN_STATUS_FAILED, RUN_STATUS_SUCCEEDED } from '@opentrons/api-client'

import {
    THERMOCYCLER_LID_MOVEMENT,
    THERMOCYCLER_EXECUTE_PROFILE,
    THERMOCYCLER_SET_BLOCK_TEMPERATURE,
    THERMOCYCLER_SET_LID_TEMPERATURE,
    HEATERSHAKER_LATCH_MOVEMENT,
    HEATERSHAKER_ROTATE,
    HEATERSHAKER_SET_TEMPERATURE,
    TEMPERATURE_MODULE_SET_TEMPERATURE
} from '/app/redux/analytics'

import type { RunStatus, RunCommandSummary } from '@opentrons/api-client'