export const NAV_STEPS = {
  BEFORE_BEGINNING: 'BEFORE_BEGINNING',
  ATTACH_PROBE: 'ATTACH_PROBE',
  CHECK_POSITIONS: 'CHECK_POSITIONS',
  DETACH_PROBE: 'DETACH_PROBE',
  RESULTS_SUMMARY: 'RESULTS_SUMMARY',
} as const
