import { SetupActions, SetupVerifications } from '../support/SetupSteps'
import { UniversalActions } from '../support/universalActions'
import { runSteps } from '../support/StepExecution'
import type { StepsList } from '../support/StepExecution'

describe('The Redesigned Create Protocol Landing Page', () => {
  beforeEach(() => {
    cy.visit('/')
    cy.verifyHomePage()
    cy.closeAnalyticsModal()
  })

  it('Tests transfer', () => {
    cy.clickCreateNew()
    cy.verifyCreateNewHeader()
    const steps: StepsList = [
      SetupVerifications.OnStep1,
      SetupVerifications.FlexSelected,
      UniversalActions.Snapshot,
      SetupActions.SelectOT2,
      SetupVerifications.OT2Selected,
      UniversalActions.Snapshot,
      SetupActions.SelectFlex,
      SetupVerifications.FlexSelected,
      UniversalActions.Snapshot,
      SetupActions.Confirm,
      SetupVerifications.OnStep2,
      SetupActions.SingleChannelPipette50,
      SetupVerifications.StepTwo50uL,
      UniversalActions.Snapshot,
      SetupActions.Confirm,
      SetupVerifications.StepTwoPart3,
      UniversalActions.Snapshot,
      SetupActions.Confirm,
      SetupVerifications.OnStep3,
      SetupActions.YesGripper,
      SetupActions.Confirm,
      SetupVerifications.Step4Verification,
      SetupActions.AddThermocycler,
      SetupVerifications.ThermocyclerImg,
      SetupActions.AddHeaterShaker,
      SetupVerifications.HeaterShakerImg,
      SetupActions.AddMagBlock,
      SetupVerifications.MagBlockImg,
      SetupActions.AddTempdeck2,
      SetupVerifications.Tempdeck2Img,
      SetupActions.Confirm,
      SetupActions.Confirm,
      SetupActions.Confirm,
      SetupActions.EditProtocolA,
      SetupActions.ChoseDeckSlotC2,
      SetupActions.AddHardwareLabware,
      SetupActions.ClickLabwareHeader,
      SetupActions.ClickWellPlatesSection,
      SetupActions.SelectArmadillo96WellPlate,
      SetupActions.ChoseDeckSlotC2Labware,
      SetupActions.AddLiquid,
      SetupActions.ClickLiquidButton,
      SetupActions.DefineLiquid,
      SetupActions.LiquidSaveWIP,
      SetupActions.WellSelector,
      SetupActions.LiquidDropdown,
      SetupVerifications.LiquidPage,
      UniversalActions.Snapshot,
      SetupActions.SelectLiquidWells,
      SetupActions.SetVolumeAndSaveforWells,
      SetupActions.ChoseDeckSlotC3,
      SetupActions.AddHardwareLabware,
      SetupActions.ClickLabwareHeader,
      SetupActions.ClickWellPlatesSection,
      SetupActions.SelectBioRad96WellPlate,
      SetupActions.ProtocolStepsH,
      SetupActions.AddStep,
      SetupVerifications.TransferPopOut,
      UniversalActions.Snapshot,
      SetupActions.ChoseSourceLabware,
      SetupActions.SelectArmadillo96WellPlateTransfer,
      SetupActions.AddSourceLabwareDropdown,
      SetupActions.WellSelector,
      SetupActions.SaveSelectedWells,
      SetupActions.ChoseDestinationLabware,
      SetupActions.SelectBiorad,
      SetupActions.SelectDestinationWells,
      SetupActions.WellSelector,
      SetupActions.SaveSelectedWells,
      SetupActions.InputTransferVolume30,
      SetupActions.Continue,
      SetupActions.PrewetAspirate,
      SetupActions.DelayAspirate,
      SetupActions.TouchTipAspirate,
      SetupActions.MixAspirate,
      SetupActions.AirGapAspirate,
      SetupVerifications.Delay,
      SetupVerifications.PreWet,
      SetupVerifications.TouchTip,
      SetupVerifications.MixT,
      SetupVerifications.AirGap,
      SetupActions.AspirateMixVolume,
      SetupActions.AspirateMixTimes,
      SetupActions.AspirateAirGapVolume,
      SetupActions.SelectDispense,
      SetupActions.DelayAspirate,
      SetupActions.TouchTipAspirate,
      SetupActions.MixAspirate,
      SetupActions.AirGapAspirate,
      SetupActions.DispenseMixVolume,
      SetupActions.DispenseMixTimes,
      SetupActions.DispenseAirGapVolume,
      SetupActions.BlowoutTransferDestination,
      SetupVerifications.ExtraDispenseTransfer,
    ]
    runSteps(steps)
    cy.contains('Save').click()
    cy.contains('button', 'Transfer').should('be.visible').click()
  })
})
